build: false

services:
  - postgresql

environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"

init:
  - "PATH=C:\\Program Files\\PostgreSQL\\9.3\\bin\\;%PATH%"
  - "SET PGUSER=postgres"
  - "SET PGPASSWORD=Password12!"
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements-win.txt"
  - ps: (new-object net.webclient).DownloadFile('http://www.stickpeople.com/projects/python/win-psycopg/2.6.1/psycopg2-2.6.1.win32-py3.4-pg9.4.4-release.exe', 'C:/psycopg.exe')
  - "PYTHON%/Scripts/easy_install.exe psycopg.exe"
  - "%PYTHON%/Scripts/pip.exe install ."

test_script:
  - "%PYTHON%/Scripts/py.test"
  - "cd tests" 
  - "%PYTHON%/Scripts/behave"
